spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_binder
    username: dcanevarollo
    password: j672fb3i

security:
  ignored:
    - "*.bundle.*"

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

